### ISSUE TITLE
Mesh extracting

### ISSUE THREAD

**Issue by denred0** [GaussianObject/GaussianObject#11]
Hi! 

Thank you for your great work. Is it possible to extract mesh as a result of the generation. I did't find any method for this.

**Comment by denred0** [comment]
I've found)

**Comment by xvbai0317** [comment]
![b9eaf4081f1e3b4890782eb526dac7e6](https://github.com/GaussianObject/GaussianObject/assets/92377243/f98e6a4b-bc21-4e79-a106-2267c15dd3be)
Hello, may I ask why the mesh generated finally has this effect? Is it because my training pictures are too few?
