### ISSUE TITLE
Requested ED25519 key fingerprint

### ISSUE THREAD

**Issue by DiamondGlassDrill** [GaussianObject/GaussianObject#2]
Cannot download recursively it says publickey permission denied?

Thanks in advance for your strong work and strong commitment to the community!!!

**Comment by GaussianObject** [comment]
Thank you for your feedback and kind words!

It looks like the issue is due to SSH key permissions. The command in the README:

```sh
# wrong code
git clone git@github.com:GaussianObject/GaussianObject.git --recursive
```

requires SSH setup. To avoid this, please use the HTTPS clone command:

```sh
git clone https://github.com/GaussianObject/GaussianObject.git --recursive
```

I'll update the README to reflect this.

Thanks again for pointing this out!

**Comment by GaussianObject** [comment]
After further investigation across several machines, we've determined that this issue may not be directly related to our repository.

Could you please provide additional logs from when you attempt to clone the repository? This information will help us enhance the accessibility of our repository. Thank you.

**Comment by DiamondGlassDrill** [comment]
Seems with HTTPS there is no issue :) so we can close it.
