### ISSUE TITLE
 Extracting Mesh from Point Cloud

### ISSUE THREAD

**Issue by mohit-choithwani** [GaussianObject/GaussianObject#22]
Upon completing the Gaussian Repair step, the final outcome yielded a point cloud file named "last.ply." Is it feasible to extract a mesh from this point cloud? Attaching the screenshot of the last.ply.

![image](https://github.com/GaussianObject/GaussianObject/assets/106359307/72a224e4-3eb8-412c-b575-1de471d7dd02)

**Comment by GaussianObject** [comment]
Gaussian splatting method isn't directly conducive to mesh generation. Recently, there have been several promising research efforts exploring the conversion from point clouds to meshes. We have experimented with some of these methods, but the results have been moderate at best.

However, should we come across or develop a more efficient and convenient method for extracting meshes in the future, we will definitely update our repository to include these advancements.

We appreciate your interest and are open to further discussions on this topic!

**Comment by mohit-choithwani** [comment]
Thank you for your reply and for sharing your insights for mesh generation.
