### ISSUE TITLE
True runtime of GaussianObject

### ISSUE THREAD

**Issue by savvaki** [GaussianObject/GaussianObject#23]
Thank you for the awesome work!

The paper makes the following statement:
```
The whole process of GaussianObject takes about 30 minutes on a GeForce RTX 3090 GPU 
for 4 input images at a 779 × 520 resolution.
```

I have the following questions:

1. Does the quote above include the Segmentation time and the depth estimation time? If not, how long do these processes take? 
2. "Segment Any 3D GAussians" preprocessing requires COLMAP. How can this approach work using COLMAP, since COLMAP usually requires more than 4 images to extract poses. How did the authors extract the poses without using the full dataset?
3. If COLMAP is a dependency, how can this approach work on new sparse datasets where COLMAP fails to extract poses? 

Thank you in advance for your reply and for releasing the code.

**Comment by GaussianObject** [comment]
Thank you for your interest and for the kind words about our work!

Regarding your questions:

1. **Segmentation and Depth Estimation Time:** The segmentation using SAM and depth estimation for four images are exceptionally quick processes, taking only a few seconds.
2. **Use of COLMAP with Sparse Images:** Our sparse view reconstruction indeed relies on poses derived from COLMAP, aligning with other methods in this research area. However, less accurate poses can still yield good results. Excitingly, recent developments, like [RayDiffusion](https://arxiv.org/abs/2402.14817), are exploring sparse view pose estimation, offering promising directions for future work.
3. **Working with New Sparse Datasets:** If you're looking to apply this approach to new sparse datasets where pose extraction via COLMAP might be challenging, consider augmenting your scenes with calibration panels or similar aids to facilitate COLMAP's pose estimation process.

We hope this clarifies your queries. Should you have further questions or need more details, feel free to reach out. We're here to assist and look forward to your contributions to the field!

**Comment by savvaki** [comment]
Thank you very much for your in-depth and speedy response. This is fantastic work and I look forward to investigating further.
