### ISSUE TITLE
submodules

### ISSUE THREAD

**Issue by jianglh-WHU** [GaussianObject/GaussianObject#31]
Hi~ Thanks for your excellent work

I wanna install the env, but I cannot find the submodule folder, which includes the necessary diff-gaussian-rasterization package. 

Can you help me to solve it?

**Comment by jianglh-WHU** [comment]
I find it's same with https://github.com/ashawkey/diff-gaussian-rasterization.

**Comment by GaussianObject** [comment]
@xvbai0317 The issues is fixed in the latest commit.
