### ISSUE TITLE
Can't load dataset

### ISSUE THREAD

**Issue by hanyangyu1021** [GaussianObject/GaussianObject#42]
I try to load mip360 dataset, but googledrive seems down?
![e64596d07abb6ab93d18795c5ce1e66](https://github.com/GaussianObject/GaussianObject/assets/86957090/4192d10d-248a-4cfa-a29b-669182eb72f6)

**Comment by runningneverstop** [comment]
Does anyone has done the dataset?
![image](https://github.com/GaussianObject/GaussianObject/assets/86957090/19a6bbb7-086c-428e-8c59-6a681934d91e)

**Comment by Kalfco** [comment]
Me too. Hi @GaussianObject , we would be very grateful if you could fix this issue. Thanks for your excellent work again!

**Comment by chensjtu** [comment]
> Me too. Hi @GaussianObject , we would be very grateful if you could fix this issue. Thanks for your excellent work again!

it seems the issue has been solved.

**Comment by GaussianObject** [comment]
Close this issue since the dataset problem is solved.
