### ISSUE TITLE
Could you release the code for testing OpenIllumination

### ISSUE THREAD

**Issue by raynehe** [GaussianObject/GaussianObject#47]
Hi! Thanks for the wonderful work!

I'm trying running 3DGS on the OpenIllumination dataset, but I'm struggling in dealing with the camera parameters. I suppose I made some mistakes about the extrincisc or intrinsics.

I'm wondering if you could share this part of data loading code?

Sorry for the bother! Thanks a lot!

**Comment by chensjtu** [comment]
I think we have checked the code, so this issue is solved.

**Comment by GaussianObject** [comment]
Close this issue since it has been solved.
