### ISSUE TITLE
AttributeError: module 'camtools.camera' has no attribute 'create_camera_ray_frames'

### ISSUE THREAD

**Issue by jiaosiyu1999** [GaussianObject/GaussianObject#5]
Thanks for the good work.

Seems the code is throwing an error on this line： 
https://github.com/GaussianObject/GaussianObject/blob/c087d48a551649fe30e2ed24a74eec80690b68ab/visual_hull.py#L252

I have looked into the source code of **camtools**, and it seems that the function `create_camera_ray_frames ` is not present in `camtools.camera`. Do you know what might cause the issue?"

**Comment by GaussianObject** [comment]
Thank you for your feedback and kind words!

The `camtools` library has updated its API, and we hadn't noticed the [pull request](https://github.com/yxlao/camtools/pull/22) until now. The function `create_camera_ray_frames` has been renamed to `create_camera_frames`.

We have updated our code accordingly.
