### ISSUE TITLE
installing these packages whose versions have conflicting dependencies

### ISSUE THREAD

**Issue by eternalland** [GaussianObject/GaussianObject#50]
when i install requirements.txt, it displays the following informaiton.

ERROR: Cannot install diff-gaussian-rasterization 0.0.0 (from ~/thesis/GaussianObject/submodules/diff-gaussian-rasterization) and diff-gaussian-rasterization 0.0.0 (from ~/thesis/GaussianObject/submodules/diff-gaussian-rasterization-w-pose) because these package versions have conflicting dependencies

**Comment by JiajieLi7012** [comment]
Hi, I encountered the same error. Can you tell me how you solved this problem? Thanks in advance.

**Comment by eternalland** [comment]
@JiajieLi7012 
Please follow this solution #49 
https://github.com/GaussianObject/GaussianObject/issues/49
