### ISSUE TITLE
Rabbit dataset

### ISSUE THREAD

**Issue by seulqxq** [GaussianObject/GaussianObject#52]
Hi,
I want to train using the rabbit dataset, using the mask generated by segment_anything.ipynb, but running 
python pred_poses.py -s data/realcap/rabbit --sparse_num 4 
gets wrong.
![image](https://github.com/user-attachments/assets/834e728f-efd1-408c-976f-8710c10146b5)
Here is the data:
![image](https://github.com/user-attachments/assets/6ff9eb26-9444-4f9c-84e4-82c3697d393d)

**Comment by TXSevenXT** [comment]
I've got this problem :(
For the moment, no solution :(

**Comment by TXSevenXT** [comment]
Find a solution in deleting "0" in the code :  
 original_masks = [np.array(Image.open(mask).resize(image.size))[:, :, 0] / 255.0 for mask, image in zip(masks, original_images)]
 Becomes original_masks = [np.array(Image.open(mask).resize(image.size))[:, :,] / 255.0 for mask, image in zip(masks, original_images)]

I will try with my others pictures and tell you if it's ok ^^
