### ISSUE TITLE
No module named 'diff_gaussian_rasterization_w_pose'

### ISSUE THREAD

**Issue by seulqxq** [GaussianObject/GaussianObject#53]
Hi @GaussianObject 

I have some doubts about 'diff_gaussian_rasterization_w_pose' module. I run the 
'pip install submodules/ diff-Gaussian_rasterization-w-pose' 
command to install it. But after installation, there is only 'diff_gaussian_rasterization' in the 'pip list'. Is there any solution?

Looking forward to your reply!

**Comment by anekha** [comment]
Same issue!

**Comment by JeffreyLuW** [comment]
I got the same issue. Is there any updates? Have you solved this problem?  @seulqxq @anekha

**Comment by seulqxq** [comment]
I referred to the method proposed by #49 and it was resolved. @JeffreyLuW 
[https://github.com/GaussianObject/GaussianObject/issues/49](url)

**Comment by JeffreyLuW** [comment]
Problem solved. Thanks a lot
