### ISSUE TITLE
The effect is not particularly good, what viewer did the author use to open the .ply file?

### ISSUE THREAD

**Issue by CypressLi01** [GaussianObject/GaussianObject#56]
![1](https://github.com/user-attachments/assets/0d5d4337-f3fa-4a37-b9d1-00b15f67a13e)
![2](https://github.com/user-attachments/assets/76a49288-d4ee-42e5-8755-27d90332c6ef)
![3](https://github.com/user-attachments/assets/441810d7-3df6-40a4-b355-b5c8c170eca2)
I used pose estimation without COLMAP for rendering, and after running the final Python scripts `train_repair.py` and `render.py`, the resulting .ply file shows a very poor modeling effect when opened.

**Comment by chensjtu** [comment]
Sorry for the late response. The renderings we report are generated by 3dgs's diff-ras module. For better visualization, we recommend using viewer in https://github.com/yzslab/gaussian-splatting-lightning to get the right rendering~

**Comment by chensjtu** [comment]
Close since this has been resolved. Feel free to reopen~
