### ISSUE TITLE
Is there anybody who was able to get results with Colmap-free Gaussian Object

### ISSUE THREAD

**Issue by merkol** [GaussianObject/GaussianObject#58]

**Comment by TXSevenXT** [comment]
No for the moment sadly (for me*).. I'm trying custom dataset and it doesn't work :(.
I've tried with rabbit but got error : 
"IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed"

**Comment by Dumeowmeow** [comment]
> No for the moment sadly (for me*).. I'm trying custom dataset and it doesn't work :(. I've tried with rabbit but got error : "IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed"

The same, have you solved it?

**Comment by Dumeowmeow** [comment]
> No for the moment sadly (for me*).. I'm trying custom dataset and it doesn't work :(. I've tried with rabbit but got error : "IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed"

Just modify line 149 in pred_poses.py:
from
original_masks = [np.array(Image.open(mask).resize(image.size))[:, :, 0] / 255.0 for mask, image in zip(masks, original_images)]
to
original_masks = [np.array(Image.open(mask).resize(image.size)) / 255.0 for mask, image in zip(masks, original_images)]

**Comment by TXSevenXT** [comment]
Thanks dude, 

I've replied to another post few days ago (https://github.com/GaussianObject/GaussianObject/issues/52) but didn't reply in this one 😅

> > No for the moment sadly (for me*).. I'm trying custom dataset and it doesn't work :(. I've tried with rabbit but got error : "IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed"
> 
> Just modify line 149 in pred_poses.py:
> from
> original_masks = [np.array(Image.open(mask).resize(image.size))[:, :, 0] / 255.0 for mask, image in zip(masks, original_images)]
> to
> original_masks = [np.array(Image.open(mask).resize(image.size)) / 255.0 for mask, image in zip(masks, original_images)]

**Comment by chensjtu** [comment]
Close this issue since it has been solved. Feel free to reopen~
