### ISSUE TITLE
renders.mp4 can not play

### ISSUE THREAD

**Issue by eternalland** [GaussianObject/GaussianObject#59]
Hi, thank you so much for your work. After executing 'Gaussian Repair,' a file named renders.mp4 was generated in the path output/gs_init/kitchen/render/ours_None, but I am unable to play it. Could you please let me know how I can play it?

![Snipaste_2024-10-13_17-52-26](https://github.com/user-attachments/assets/8b14ca32-d06a-49a9-8dbd-5c23f9580c05)

**Comment by chensjtu** [comment]
Hey! This may be due to FFmpeg's different encoding. Maybe you should use ""-pix_fmt", "yuv420p"," # Set pixel format for compatibility" to make the machine read it.

**Comment by eternalland** [comment]
@chensjtu 
Thank you so much, it worked successfully.
execute this command, "ffmpeg -i renders.mp4 -pix_fmt yuv420p output.mp4", 
then execute "ffplay output_fixed.mp4" for playback, or transferred the output.mp4 file from Ubuntu to Windows for playback
