### ISSUE TITLE
For scenes?

### ISSUE THREAD

**Issue by nivibilla** [GaussianObject/GaussianObject#6]
Can this be used to replicate whole scenes?

**Comment by GaussianObject** [comment]
Thank you for your interest in our work! Our model is primarily designed for object reconstruction, but the Gaussian Repair Model can indeed be applied to background repair as well. We are currently exploring this application and planning to conduct trials in this area.

**Comment by nivibilla** [comment]
Amazing. Thank you! Looking forward to it.
