### ISSUE TITLE
Made a Colab Notebook

### ISSUE THREAD

**Issue by jjangsangy** [GaussianObject/GaussianObject#9]
I made a colab notebook for people who don't own GPU's with enough VRAM for LORA training.

https://colab.research.google.com/drive/1WIZgM--tJ3aq25t9g238JAuAoXrQYVMs?usp=sharing

**Comment by GaussianObject** [comment]
Thank you for creating and sharing the Colab notebook! Your contribution is greatly appreciated, and we plan to include a link to your notebook in our README to help make our project more accessible to the community. We're thankful for your support.

**Comment by jjangsangy** [comment]
No problem, glad I could be of help!
